import {chromium} from '@playwright/test';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:3000');
await page.getByRole('button',{name:'Play',exact:true}).waitFor();
await page.waitForFunction(()=>!document.querySelector('.play-button')?.disabled);
await page.screenshot({path:'/tmp/afterlight-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Play',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.timecode')?.textContent?.startsWith('00:02'));
await page.getByRole('button',{name:'Pause',exact:true}).click();
await page.screenshot({path:'/tmp/afterlight-playing.png',fullPage:true});
await page.getByRole('button',{name:'Christmas A little holiday magic'}).click();
await page.getByRole('switch',{name:'Snowfall'}).waitFor();
await page.getByRole('button',{name:'Focus Jaro',exact:true}).click();
if(await page.locator('.focus-chip').textContent()!=='Jaro')throw new Error('District focus failed');
await page.getByRole('button',{name:'Reset map view'}).click();
await page.screenshot({path:'/tmp/afterlight-christmas.png',fullPage:true});
await page.getByRole('button',{name:'Export video'}).click();
await page.locator('select').nth(0).selectOption('720');
await page.locator('select').nth(1).selectOption('10');
const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/exports')&&r.request().method()==='POST');
await page.getByRole('button',{name:'Render video',exact:true}).click();
const response=await responsePromise;const job=await response.json();console.log('EXPORT',JSON.stringify(job));
if(!response.ok())throw new Error(JSON.stringify(job));
await page.getByRole('button',{name:'Close dialog'}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/afterlight-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile overflow');
console.log('ERRORS',JSON.stringify(errors));
if(errors.length)throw new Error(errors.join('\n'));
await browser.close();
