import {chromium} from '@playwright/test';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
try {
 const page=await browser.newPage({viewport:{width:1366,height:768}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3000');
 await page.waitForFunction(()=>!document.querySelector('.play-button')?.disabled);
 if(await page.locator('.workspace-heading').count())throw new Error('Removed heading returned');
 if(await page.locator('.sidebar').count())throw new Error('Settings must be closed by default');
 await page.getByRole('button',{name:'Christmas A little holiday magic'}).click();
 const snow=page.getByTestId('snowfall');
 if(await snow.locator('path').count()!==120)throw new Error('Missing snowflakes');
 const before=await snow.locator('path').first().getAttribute('transform');
 await page.getByRole('button',{name:'Play',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.timecode')?.textContent?.startsWith('00:02'));
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 if(before===await snow.locator('path').first().getAttribute('transform'))throw new Error('Snow is static');
 await page.getByRole('button',{name:'Visualizer settings',exact:true}).click();
 await page.getByRole('button',{name:'Cut all power',exact:true}).click();
 if(!await page.locator('[data-district]').evaluateAll(nodes=>nodes.every(n=>Number(n.dataset.power)===0)))throw new Error('District cut failed');
 await page.getByRole('button',{name:'Reconnect all',exact:true}).click();
 await page.getByRole('switch',{name:'Snowfall'}).click();
 if(await snow.count())throw new Error('Snowfall toggle failed');
 await page.getByRole('switch',{name:'Snowfall'}).click();
 await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'Rain Rain over the city'}).click();
 const rain=page.getByTestId('rainfall');
 if(await rain.locator('line').count()!==160)throw new Error('Missing rain');
 const rainBefore=await rain.locator('line').first().getAttribute('y1');
 await page.getByRole('button',{name:'Play',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.timecode')?.textContent?.startsWith('00:04'));
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 if(rainBefore===await rain.locator('line').first().getAttribute('y1'))throw new Error('Rain is static');
 const mapGroup=page.locator('.scene-player svg > g').first();
 const position=await mapGroup.getAttribute('transform');
 await page.mouse.move(360,210);await page.mouse.down();await page.mouse.move(430,240,{steps:5});await page.mouse.up();
 if(position===await mapGroup.getAttribute('transform'))throw new Error('Map pan failed');
 await page.getByRole('button',{name:'Reset map view'}).click();
 const dimensions=await page.evaluate(()=>({page:document.documentElement.scrollHeight,height:innerHeight,mapWidth:document.querySelector('.map-frame').clientWidth,width:innerWidth,dock:document.querySelector('.transport').getBoundingClientRect().bottom}));
 if(dimensions.page>dimensions.height||dimensions.mapWidth!==dimensions.width||dimensions.dock>dimensions.height)throw new Error(JSON.stringify(dimensions));
 console.log('Desktop fullscreen layout:',dimensions);
 await page.screenshot({path:'/tmp/brownout-studio-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Visualizer settings',exact:true}).click();
 await page.screenshot({path:'/tmp/brownout-studio-settings.png',fullPage:true});
 await page.getByRole('button',{name:'Close dialog'}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/tmp/brownout-studio-mobile.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight))throw new Error('Mobile overflow');
 await page.getByRole('button',{name:'Visualizer settings',exact:true}).click();
 await page.getByRole('switch',{name:'Rainfall'}).click();
 if(await rain.count())throw new Error('Rainfall toggle failed');
 await page.getByRole('switch',{name:'Rainfall'}).click();
 await page.getByRole('button',{name:'Close dialog'}).click();
 const chooserPromise=page.waitForEvent('filechooser');
 await page.locator('.map-upload').click();
 await (await chooserPromise).setFiles('/tmp/afterlight-test.wav');
 await page.waitForFunction(()=>document.querySelector('.track-details strong')?.textContent==='afterlight-test');
 await page.getByRole('button',{name:'Export video'}).click();
 await page.getByLabel('Resolution',{exact:true}).selectOption('720');
 const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/exports')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Render video',exact:true}).click();
 const response=await responsePromise,job=await response.json();
 if(!response.ok())throw new Error(JSON.stringify(job));
 console.log('Studio export:',job.id);
 await page.getByRole('link',{name:'Download video'}).waitFor({timeout:180000});
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('Full-map layout, floating dock, settings, pan, snow, rain, upload, mobile, and MP4 export passed.');
}finally{await browser.close();}
