import {chromium} from '@playwright/test';
import {getVideoMetadata} from '@remotion/renderer';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
try {
 const page=await browser.newPage({viewport:{width:1366,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000');
 await page.waitForFunction(()=>!document.querySelector('.play-button')?.disabled);
 await page.locator('input[type=file]').setInputFiles('/tmp/afterlight-test.wav');
 await page.waitForFunction(()=>document.querySelector('.track-details strong')?.textContent==='afterlight-test');
 await page.getByRole('button',{name:'Moonlight Cool & understated'}).click();
 await page.getByRole('button',{name:'Visualizer settings',exact:true}).click();
 await page.getByRole('switch',{name:'Map labels'}).click();
 if(await page.getByRole('button',{name:'Focus Jaro'}).count())throw new Error('Labels toggle failed');
 await page.getByRole('switch',{name:'Map labels'}).click();
 await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'Export video'}).click();
 await page.getByLabel('Resolution',{exact:true}).selectOption('1080');
 const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/exports')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Render video',exact:true}).click();
 const response=await responsePromise,job=await response.json();
 if(!response.ok())throw new Error(JSON.stringify(job));
 console.log('Rendering uploaded audio:',job.id);
 await page.getByRole('link',{name:'Download video'}).waitFor({timeout:180000});
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('link',{name:'Download video'}).click();
 const download=await downloadPromise;await download.saveAs('/tmp/afterlight-verified-1080p.mp4');
 const metadata=await getVideoMetadata('/tmp/afterlight-verified-1080p.mp4');
 if(metadata.width!==1920||metadata.height!==1080||metadata.audioCodec!=='aac'||metadata.codec!=='h264')throw new Error('Incorrect export metadata');
 console.log('Verified downloaded export:',metadata);
 await page.getByRole('button',{name:'Create another video'}).click();
 await page.getByRole('button',{name:'Render video',exact:true}).waitFor();
 await page.getByRole('button',{name:'Close dialog'}).click();
 await page.locator('input[type=file]').setInputFiles({name:'broken.wav',mimeType:'audio/wav',buffer:Buffer.from('not audio')});
 await page.getByRole('alert').waitFor();
 if(await page.locator('.track-details strong').textContent()!=='afterlight-test')throw new Error('Invalid upload replaced valid soundtrack');
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('Upload, invalid-file recovery, labels, 1080p export, download, repeat-export flow: passed.');
} finally {await browser.close();}
